In [2]:
import numpy as np
import pandas as pd


In [8]:
'''
Q1 Create a vector of positive odd integers less that 100. Find if there are numbers greater than 80

'''
import numpy as np
odd_numbers = np.arange(1, 100, 2)
greater_than_80 = odd_numbers[odd_numbers > 80]
print("vector of positive odd integers less than 100:", (odd_numbers))
print("Numbers greater than 80:", (greater_than_80))

vector of positive odd integers less than 100: [ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]
Numbers greater than 80: [81 83 85 87 89 91 93 95 97 99]


In [15]:
'''
Q2 Remove the values greater than 60 and less than 80 in Q1 
'''
import numpy as np
odd_numbers = np.arange(1, 100, 2)
remove_values = odd_numbers[~((odd_numbers > 60) & (odd_numbers < 80))]
print(remove_values)


[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 81 83 85 87 89 91 93 95 97 99]


In [17]:
'''
Q3 Find the mean, standard deviation of the resulting vector in Q2
'''
import numpy as np
odd_numbers = np.arange(1, 100, 2)
remove_values = odd_numbers[~((odd_numbers > 60) & (odd_numbers < 80))]
mean = np.mean(remove_values)
std_dvn = np.std(remove_values)
print("mean", mean)
print("standard deviation", std_dvn)



mean 45.0
standard deviation 30.133038346638727


In [27]:
'''
Q4  X = [“John”, “Jenny”, “Ron” , “Mary”]. Give two ways to access Ron.
'''
X = ['John', 'Jenny', 'Ron' , 'Mary']
print(X[2])
print(X[-2])

Ron
Ron


In [34]:
'''
Q5  You have: 
Vec1 = [“John”, “Jenny”, “Mary”, “Ron”]. 
Use this list to create this output.

Hello John!  Hello Jenny!  Hello Mary!  Hello Ron 

'''
Vec1 = ['John', 'Jenny', 'Mary', 'Ron']
for name in Vec1:
    print(f"Hello {name}!", end=" ")

Hello John! Hello Jenny! Hello Mary! Hello Ron! 

In [30]:
'''
Q6 Write a function to return mean, standard deviation and median of a list. Verify with example
'''
import numpy as np
list_numbers = [1,3,5,7,9]
def calculate_list(numbers):
    mean = np.mean(list_numbers)
    stand_dev= np.std(list_numbers)
    median = np.median(list_numbers)
    return mean, std, median
mean, std, median = calculate_list(list_numbers)
print("mean", mean)
print("standard deviation", std)
print("median", median)

mean 5.0
standard deviation 2.8284271247461903
median 5.0


In [33]:
'''
Q7 Create two matrices from the given vectors
X1 = [2,3,7,1,6,2,3,5,1] and X2 = [3,2,9,0,7,8,5,8,2]. Find the matrix product.
'''
import numpy as np
X1 = np.array([[2,3,7,1,6,2,3,5,1]])
X2 = np.array([[3,2,9,0,7,8,5,8,2]])
X1 = X1.reshape(3, 3)
X2 = X2.reshape(3, 3)
matrix_product = np.dot(X1, X2)
print(matrix_product)

[[41 81 56]
 [13 60 61]
 [14 49 69]]


In [39]:
'''
Q8: Define a function called pword that takes a word and prints characters from 
the word. 
'''
def pword(word):
    for chars in word:
        print(chars)
pword("Happy")

H
a
p
p
y


In [40]:
'''
Create a function that takes list1 = [-11, -8, 4, 15, 20] 
and returns a list of even numbers from list1.
'''
def elist(a):
    new_list = []
    for item in a:
        if (item%2 == 0):
            new_list.append(item)
    return new_list
list1 = [-11, -8, 4, 15, 20]
print(elist(list1))

[-8, 4, 20]
