### Assignment 4

In [5]:
# Q1
'''
From a given matrix fetch 4,23,29,10
''' 
import numpy as np
arr = np.arange(32).reshape((8, 4))
print(arr)
result = arr[[1, 5, 7, 2], [0, 3, 1, 2]]
print("Fetched values:", result)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
Fetched values: [ 4 23 29 10]


In [4]:
'''
Q2. How to get the minimum, 25th percentile, median, 75th, and max of a numeric series?
'''
import numpy as np

data = np.array([10, 20, 30, 40, 50, 60, 70, 80])

print("Minimum:", np.min(data))                   
print("25th Percentile:", np.percentile(data, 25)) 
print("Median:", np.median(data))                  
print("75th Percentile:", np.percentile(data, 75)) 
print("Maximum:", np.max(data))  

Minimum: 10
25th Percentile: 27.5
Median: 45.0
75th Percentile: 62.5
Maximum: 80


In [3]:
'''
Q3. x = np.array([[3, 7, 5, 5],
      [0, 1, 5, 9],
      [3, 0, 5, 0]])  
      
a. Find the dimension of x
b. Find the position of minimum in x
c. Find the position of minimum in x across row
d. Find the position of minimum in x across column
'''

import numpy as np

x = np.array([[3, 7, 5, 5],
              [0, 1, 5, 9],
              [3, 0, 5, 0]])

print("a. Dimension (shape) of x:", x.shape)

min_index = np.unravel_index(np.argmin(x), x.shape)
print("b. Position of overall minimum value:", min_index)

row_min_indices = np.argmin(x, axis=1)
print("c. Position of minimum in each row:", row_min_indices)

col_min_indices = np.argmin(x, axis=0)
print("d. Position of minimum in each column:", col_min_indices)


a. Dimension (shape) of x: (3, 4)
b. Position of overall minimum value: (np.int64(1), np.int64(0))
c. Position of minimum in each row: [0 0 1]
d. Position of minimum in each column: [1 2 0 2]


In [2]:
'''
Q4.  Given two series

1. Get the items of series A preset in series B

2. Get all items of series A and Series B not common to both
'''

import pandas as pd

series_a = pd.Series([1, 2, 3, 4, 5])
series_b = pd.Series([4, 5, 6, 7, 8])

common_items = series_a[series_a.isin(series_b)]
print("1. Items of Series A that are also in Series B:")
print(common_items.tolist())

not_common_items = pd.Series(
    list(set(series_a) ^ set(series_b)) 
)
print("\n2. Items NOT common to both Series A and Series B:")
print(not_common_items.tolist())


1. Items of Series A that are also in Series B:
[4, 5]

2. Items NOT common to both Series A and Series B:
[1, 2, 3, 6, 7, 8]


In [ ]:
'''
Q5 From the following matrix create the matirx of the form 
'''
#Input matrix
arr = np.empty((8, 4))
# Output
array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])


'''
